[project]
dynamic = ["dependencies"]
name = "nlp_chat_bot"
version = "0.0.1"
authors = [
  {name = "Maxime Cabrit"},
  {name = "Ethan Pinto"},
  {name = "Robin Meneust"},
]
description = "Chat Bot with RAG"
readme = "README.md"